### ISSUE TITLE
Int conversion bug when converting intensities to xarray

### ISSUE THREAD

**Issue by KristianJS** [skaderli/WaveBreaking#3]
* WaveBreaking version: main 
* Python version: 3.10
* Operating System: Unix

### Description

I wanted to create an xarray file capturing the intensity of anticyclonic northern hemispheric wavebreaking at every time/lat/lon. The intensities should always be >0, but after converting to xarray, the intensities in the array were coming out as positive and negative, with a min of -128 and a max of 127. 

### Example

I followed the example code for how to create the relevant xarray.

```
rwb = gpd.read_parquet("./era5/era5_pv_streamers_340K_1959-2022.parquet")

tropospheric = rwb[abs(rwb.mean_var) < 2]
anticyclonic = tropospheric[((tropospheric.level > 0) & (tropospheric.intensity > 0) | # Northern hemisphere
                    (tropospheric.level < 0) & (tropospheric.intensity < 0))] # Southern hemisphere

nh = anticyclonic[np.asarray(list(anticyclonic.com))[:,1] > 0] # restrict to northern hemisphere

# create dataset with correct dimensions
times = pd.date_range(start='1959-01-01T00', end="2022-12-31T18", freq='6H')
lats = np.arange(-89,90,1)
lons = np.arange(-180,180,1)
da = xr.DataArray(dims=["time", "lat", "lon"], coords={"time":times, "lat":lats, "lon":lons}).to_dataset(name="init")

da["tropos"] = wb.to_xarray(data = da.init, events = nh, flag='intensity')
da = da.drop("init")
```

Running `print(nh.intensity.values.min()` returns 0.0 as expected, but running `print(da['tropos'].values.flatten().min())` returns `np.int8(-128)`.

### The problem

The offending line in the `to_xarray` function is the following: `data_flagged = data_flagged.astype("int8")`. This is fine if `flag = 'ones'`, but generates a signed-unsigned float/int conversion bug when running `flag = 'intensity'`. I solved this in a local install by just adding an `if flag == 'intensity'` statement, and saving as float64 in that case. Maybe there are better ways.

**Comment by skaderli** [comment]
Hi Kristian

Please excuse my late response. I'm actually not working on this project anymore and have had to find some time to look at it.

Thanks a lot for pointing that out! I initially added the line `data_flagged = data_flagged.astype("int8")` to reduce the size of the `xarray.Dataset` when using the `flag='ones'`. Of course, this does not work when using other flag names. I added an `if flag=='ones' ` statement for the conversion to an `int8`. 

I committed the change in the latest release (v0.3.8). Please let me know if you still experience issues converting the event dataframes to a xarray.
